title: Metabench
email: ldionne.2@gmail.com
description: "A collection of metaprogramming benchmarks."
url: "http://ldionne.github.io/metabench"
baseurl: "/metabench"

collections:
  type:
    name: Pure Type
    output: true
    active: true
  hetero:
    name: Heterogeneous
    output: true
